# This workflow will install IC and run all the tests with pytest

name: Test suite

on:
  push:
  pull_request:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        #platform: [ubuntu-18.04, macos-latest]
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Get LFS files
      run: git lfs pull
    # - name: Fix Conda permissions on macOS
    #   run: sudo chown -R $UID $CONDA
    #   if: runner.os == 'macOS'

    - name: Install IC
      run: |
        source $CONDA/etc/profile.d/conda.sh
        source manage.sh work_in_python_version_no_tests ${{ matrix.python-version }}


    - name: Run tests
      run: |
        set -o pipefail # necessary for test failure to propagate to `tee`
        source $CONDA/etc/profile.d/conda.sh
        source manage.sh work_in_python_version_no_tests ${{ matrix.python-version }}
        PYTEST_ADDOPTS=--color=yes HYPOTHESIS_PROFILE=travis-ci bash manage.sh run_tests_par | tee pytest_output

    - name: Warning summary
      run: |
        ./scripts/check_warnings pytest_output | tee warnings
        if [ -s warnings ]; then
            echo "::warning ::There are warnings raised in the test suite"
        else
            echo "No warnings were raised."
        fi
